name: Daily Digest Scheduler
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      force:
        description: 'Bypass time window (1=yes, 0=no)'
        required: false
        default: '0'
      target_email:
        description: 'Only send to this email (optional)'
        required: false
        default: ''

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm install

      - name: Run daily digest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          FORCE_SEND: ${{ github.event.inputs.force }}
          TARGET_EMAIL: ${{ github.event.inputs.target_email }}
        run: node index.js
